#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("/components/toolchain/lib/toolchain.lib.yml", "create_toolchain_components")

#@yaml/text-templated-strings
---
#@ def params():
toolchain_name: host
triple: x86_64-pc-linux-gnu
binutils_version: "2.35"
gdb_version: "9.2"
gcc_version: "10.1.0"
gcc_sysroot: /
extra_gcc_configure_options:
  - --without-cloog
  - --enable-libsanitizer
  - --enable-libssp
  - --enable-shared
  - --enable-libatomic
  - --enable-libquadmath
  - --enable-esp
  - --disable-libstdcxx-pch
  - --enable-threads=posix
  - --enable-__cxa_atexit
  - --enable-clocale=gnu
  - --disable-altivec
  - --disable-fixed-point
  - --enable-targets=all
  - --enable-libgomp
  - --disable-libmudflap
  - --disable-libssp
  - --disable-systemtap
  - --enable-lto
  - --without-isl
  - --enable-default-pie
  - --enable-default-ssp
  - --enable-libmpx
  - CFLAGS_FOR_TARGET="-I/usr/include/tirpc (@= data.values.use_old_glibc_cflags @)"
  - CXXFLAGS_FOR_TARGET="-I/usr/include/tirpc (@= data.values.use_old_glibc_cflags @)"
  - LDFLAGS_FOR_TARGET="(@= data.values.use_old_glibc_lflags @) -Wl,-z,origin -Wl,--enable-new-dtags -Wl,-rpath,$RPATH_PLACEHOLDER/lib"
extra_binutils_configure_options:
  - --enable-gold=default
extra_gcc_make_variables: LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components: #@ create_toolchain_components(**params())
