#@ load("@ytt:overlay", "overlay")
#@ load("/lib/cmake.lib.yml", "typical_cmake_builds")

---
#@ def build_args():
build_dependencies:
  - cmake
dependencies:
  - toolchain/host/gcc
  - clang-release
use_asan: false
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  ui/adaptagrams:
    repository: ui/adaptagrams
    default_build: optimized
    builds: #@ typical_cmake_builds(**build_args())
