#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("/lib/create_component.lib.yml", "single_build_component")

#@ source_url = "https://download.savannah.gnu.org/releases/freetype/freetype-2.10.2.tar.gz"

#@yaml/text-templated-strings
---
#@ def freetype_args():
configure: |
  mkdir -p "$BUILD_DIR"
  extract.sh --into "$BUILD_DIR" "(@= source_url @)"

  cd "$BUILD_DIR"
  ./configure \
    --disable-freetype-config \
    --enable-biarch-config \
    --enable-shared \
    --without-brotli \
    --without-bzip2 \
    --without-harfbuzz \
    --without-png \
    --disable-static \
    --prefix="$ORCHESTRA_ROOT" \
    CC="cc -fuse-ld=gold" \
    LDFLAGS="(@= data.values.use_old_glibc_lflags @) (@= data.values.modern_linker_flags @) -Wl,-rpath,$RPATH_PLACEHOLDER/lib" \
    CFLAGS="(@= data.values.use_old_glibc_cflags @)"
build_system: make
dependencies:
  - clang-release
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  ui/freetype: #@ single_build_component(**freetype_args())
