#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("/lib/create_component.lib.yml", "single_build_component")

#@ source_url = "https://libbsd.freedesktop.org/releases/libbsd-0.10.0.tar.xz"

#@yaml/text-templated-strings
---
#@ def libbsd_args():
configure: |
  extract.sh --into "$BUILD_DIR" "(@= source_url @)"
  mkdir -p "$BUILD_DIR"
  cd "$BUILD_DIR"
  ./configure \
    --disable-static \
    --prefix="$ORCHESTRA_ROOT" \
    LDFLAGS="(@= data.values.use_old_glibc_lflags @) (@= data.values.modern_linker_flags @) -Wl,-rpath,$RPATH_PLACEHOLDER/lib" \
    CFLAGS="(@= data.values.use_old_glibc_cflags @)"
build_system: make
build_dependencies:
  - host-c-toolchain
  - glibc
#@ end

#@overlay/match by=overlay.all
#@overlay/match-child-defaults missing_ok=True
---
components:
  ui/libbsd: #@ single_build_component(**libbsd_args())
