#@ load("@ytt:overlay", "overlay")
#@ load("/lib/cmake.lib.yml", "cmake_boost_configuration", "typical_cmake_builds")

---
#@ def build_args():
extra_cmake_args:
  - -DQML_PLUGIN_INSTALL_DIRECTORY="$ORCHESTRA_ROOT/qml"
build_dependencies:
  - cmake
dependencies:
  - toolchain/host/gcc
  - clang-release
  - ui/qt
use_asan: false
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  ui/quickqanava:
    repository: ui/quickqanava
    builds: #@ typical_cmake_builds(**build_args())
