#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@ load("/lib/create_component.lib.yml", "single_build_component")

#@yaml/text-templated-strings
---
#@ def boost():
license: LICENSE_1_0.txt
configure: |
  mkdir -p "$BUILD_DIR"

  extract.sh --into "$BUILD_DIR" "https://dl.bintray.com/boostorg/release/1.71.0/source/boost_1_71_0.tar.bz2"
  patch-if-exists "${ORCHESTRA_DOTDIR}/patches/boost-1.63.0-icl-disable-LessThanComparableConcept.patch" "$BUILD_DIR"
  cd "$BUILD_DIR" && ./bootstrap.sh --prefix="$ORCHESTRA_ROOT" --with-libraries=test
install: |
  cd "$BUILD_DIR"
  export ORIGIN='$ORIGIN'
  ./b2 \
    --prefix="${DESTDIR}${ORCHESTRA_ROOT}" \
    --ignore-site-config toolset='clang' \
    cxxflags='(@= data.values.use_old_glibc_cflags @) (@= data.values.regular_cxx_flags @)' \
    linkflags='(@= data.values.use_old_glibc_lflags @) (@= data.values.regular_linker_flags @) -Wl,-rpath=$ORIGIN/../lib'
  ./b2 \
    --prefix="${DESTDIR}${ORCHESTRA_ROOT}" \
    --ignore-site-config toolset='clang' \
    cxxflags='(@= data.values.regular_cxx_flags @)' \
    linkflags='(@= data.values.regular_linker_flags @) -Wl,-rpath=$ORIGIN/../lib' \
    install
build_dependencies:
  - host-cxx-toolchain
  - glibc
dependencies:
  - host-libcxx
  - libunwind
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  boost: #@ single_build_component(**boost())
