#@ load("@ytt:template", "template")
#@ load("@ytt:overlay", "overlay")

#@ load("/lib/create_component.lib.yml", "single_build_component")

#@ load("/global_options.lib.yml", "options")

#@ def _boost():
configure: |
  mkdir -p "$BUILD_DIR"

  extract.sh --into "$BUILD_DIR" "https://dl.bintray.com/boostorg/release/1.71.0/source/boost_1_71_0.tar.bz2"
  patch-if-exists "${ORCHESTRA_DOTDIR}/patches/boost-1.63.0-icl-disable-LessThanComparableConcept.patch" "$BUILD_DIR"
  cd "$BUILD_DIR" && ./bootstrap.sh --prefix="$ORCHESTRA_ROOT" --with-libraries=test
install: |
  cd "$BUILD_DIR"
  export ORIGIN='$ORIGIN'
  ./b2 \
    --prefix="${DESTDIR}${ORCHESTRA_ROOT}" \
    --ignore-site-config toolset='clang' \
    cxxflags='(@= options["use_old_glibc_cflags"] @) (@= options["regular_cxx_flags"] @)' \
    linkflags='(@= options["use_old_glibc_lflags"] @) (@= options["regular_linker_flags"] @) -Wl,-rpath=$ORIGIN/../lib'
  ./b2 \
    --prefix="${DESTDIR}${ORCHESTRA_ROOT}" \
    --ignore-site-config toolset='clang' \
    cxxflags='(@= options["regular_cxx_flags"] @)' \
    linkflags='(@= options["regular_linker_flags"] @) -Wl,-rpath=$ORIGIN/../lib' \
    install
dependencies:
  - clang-release
  - toolchain/host/gcc
  - libunwind
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
#@yaml/text-templated-strings
---
components:
  boost: #@ single_build_component(**_boost())
