#@ load("@ytt:overlay", "overlay")

#@ load("/lib/cmake.lib.yml", "cmake_boost_configuration", "typical_cmake_builds")

---
#@ def build_args():
extra_cmake_args: #@ cmake_boost_configuration
build_dependencies:
  - cmake
dependencies:
  - clang-release
  - llvm
  - revng
  - revng-c
  - boost
use_asan: false
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  caliban:
    repository: caliban
    default_build: optimized
    builds: #@ typical_cmake_builds(**build_args())
