#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("/lib/create_component.lib.yml", "single_build_component")

#@ source_url = "https://sourceware.org/elfutils/ftp/elfutils-0.148.tar.bz2"

#@yaml/text-templated-strings
---
#@ def elfutils_args():
configure: |
  mkdir -p "$BUILD_DIR"
  extract.sh --into "$BUILD_DIR" "(@= source_url @)"
  cd "$BUILD_DIR"
  ./configure \
    --disable-nls \
    --disable-thread-safety \
    --program-prefix=eu- \
    --with-zlib \
    --without-bzlib \
    --without-lzma \
    --prefix="$ORCHESTRA_ROOT" \
    CFLAGS="(@= data.values.use_old_glibc_cflags @) -Wno-error" \
    LDFLAGS="(@= data.values.use_old_glibc_lflags @) (@= data.values.modern_linker_flags @) -Wl,-rpath,$RPATH_PLACEHOLDER/lib"
build_system: make
dependencies:
  - toolchain/host/gcc
  - zlib
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  elfutils: #@ single_build_component(**elfutils_args())
