#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("/lib/create_component.lib.yml", "single_build_component")

#@ source_url = "https://github.com/libffi/libffi/releases/download/v3.3/libffi-3.3.tar.gz"

#@yaml/text-templated-strings
---
#@ def _libffi_args():
configure: |
  mkdir -p "$BUILD_DIR"
  extract.sh --into "$BUILD_DIR" (@= source_url @)

  cd "$BUILD_DIR"
  ./configure \
    --disable-multi-os-directory \
    --disable-static \
    --disable-pax_emutramp \
    --disable-debug \
    --prefix="$ORCHESTRA_ROOT" \
    CFLAGS="(@= data.values.use_old_glibc_cflags @)" \
    LDFLAGS="(@= data.values.use_old_glibc_lflags @) (@= data.values.modern_linker_flags @) -Wl,-rpath,$RPATH_PLACEHOLDER/lib"
build_system: make
dependencies:
  - toolchain/host/gcc
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  libffi: #@ single_build_component(**_libffi_args())