#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("/lib/create_component.lib.yml", "single_build_component")

#@ source_url = "https://download.savannah.nongnu.org/releases/libunwind/libunwind-1.4.0.tar.gz"

#@yaml/text-templated-strings
---
#@ def libunwind_args():
configure: |
  mkdir -p "$BUILD_DIR"
  extract.sh --into "$BUILD_DIR" (@= source_url @)
  cd "$BUILD_DIR"
  export CC="cc -fcommon"
  ./configure \
    --enable-cxx-exceptions \
    --disable-coredump \
    --disable-ptrace \
    --enable-setjmp \
    --disable-debug-frame \
    --disable-documentation \
    --disable-minidebuginfo \
    --disable-static \
    --disable-conservative_checks \
    --disable-debug \
    --prefix="$ORCHESTRA_ROOT" \
    CFLAGS="(@= data.values.use_old_glibc_cflags @)" \
    LDFLAGS="(@= data.values.use_old_glibc_lflags @) (@= data.values.modern_linker_flags @) -Wl,-rpath,$RPATH_PLACEHOLDER/lib"
build_system: make
build_dependencies:
  - gcc-host-toolchain
  - glibc
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  libunwind: #@ single_build_component(**libunwind_args())
