#@ load("@ytt:overlay", "overlay")
#@ load("/lib/cmake.lib.yml", "cmake_boost_configuration", "typical_cmake_builds")

---
#@ def build_args():
extra_cmake_args: #@ cmake_boost_configuration
build_dependencies:
  - revng-qa
  - glibc
dependencies:
  - toolchain/host/gcc
  - llvm
  - qemu
  - boost
  - clang-release
use_asan: false
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  revng:
    repository: revng
    default_build: optimized
    builds: #@ typical_cmake_builds(**build_args())
