#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("/lib/create_component.lib.yml", "single_build_component")

#@ source_url = "https://zlib.net/zlib-1.2.11.tar.gz"

#@yaml/text-templated-strings
---
#@ def zlib_args():
license: README
configure: |
  mkdir -p "$BUILD_DIR"
  extract.sh --into "$BUILD_DIR" (@= source_url @)
  cd "$BUILD_DIR"
  export CFLAGS="(@= data.values.use_old_glibc_cflags @)"
  export LDFLAGS="(@= data.values.use_old_glibc_ldflags @)"
  ./configure \
    --shared \
    --uname=linux \
    --prefix="$ORCHESTRA_ROOT"
build_system: make
build_dependencies:
  - host-c-toolchain
  - glibc
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  zlib: #@ single_build_component(**zlib_args())
