#@ load("/lib/util.lib.yml", "datavalue")

#! Do not push upstream components defined here.
#! You should define them in a separate file and use overlay annotations.
components: {}
add_to_path:
  - $ORCHESTRA_ROOT/bin
  - $ORCHESTRA_DOTDIR/support
environment:
  - JOBS: #@ str(datavalue("parallelism"))
  - QML2_IMPORT_PATH: $ORCHESTRA_ROOT/qml
  - QT_PLUGIN_PATH: $ORCHESTRA_ROOT/plugins
  - PKG_CONFIG_PATH: $ORCHESTRA_ROOT/lib/pkgconfig:$ORCHESTRA_ROOT/share/pkgconfig${PKG_CONFIG_PATH:+:${PKG_CONFIG_PATH}}
  - INSTALL_LINK_ONLY_PATH: $ORCHESTRA_ROOT/link-only
  - LIBGL_DRIVERS_PATH: $ORCHESTRA_ROOT/lib/dri${LIBGL_DRIVERS_PATH:+:${LIBGL_DRIVERS_PATH}}
  - PYTHONPATH: $ORCHESTRA_ROOT/lib/python${PYTHONPATH:+:${PYTHONPATH}}

paths: #@ datavalue("paths", default={})
remote_base_urls: #@ datavalue("remote_base_urls")
binary_archives: #@ datavalue("binary_archives")
