#@ def prefixes():
- x86-64
- i686
#@ end

#@yaml/text-templated-strings
---
#@ def macosx_clang_components():
#@ for prefix in prefixes():
macos/(@= prefix @)-clang:
  builds:
    default:
      configure: |
        mkdir -p "$BUILD_DIR"
      install: |
        rm -f "${TMP_ROOT}${ORCHESTRA_ROOT}/bin/(@= prefix @)-apple-darwin11-clang"
        cp "$ORCHESTRA_DOTDIR/support/add-sysroot-wrapper.sh" "${TMP_ROOT}${ORCHESTRA_ROOT}/bin/(@= prefix @)-apple-darwin11-clang"
        rm -f "${TMP_ROOT}${ORCHESTRA_ROOT}/bin/(@= prefix @)-apple-darwin11-clang++"
        cp "$ORCHESTRA_DOTDIR/support/add-sysroot-wrapper.sh" "${TMP_ROOT}${ORCHESTRA_ROOT}/bin/(@= prefix @)-apple-darwin11-clang++"
      dependencies:
        - clang-release
        - macos/sdk
        - macos/(@= prefix @)-ld64
#@ end
#@ end
