#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:template", "template")

#@ load("/components/macos/libtapi.lib.yml", "libtapi_component")
#@ load("/components/macos/sdk.lib.yml", "macosx_sdk_component")
#@ load("/components/macos/ld64.lib.yml", "ld64_components")
#@ load("/components/macos/clang.lib.yml", "macosx_clang_components")

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  macos/libtapi: #@ libtapi_component()
  macos/sdk: #@ macosx_sdk_component()
  _: #@ template.replace(ld64_components())
  _: #@ template.replace(macosx_clang_components())
