#@ sdk_archive_name = "Xcode_9.xip-MacOSX.sdk.tar.gz"

#@yaml/text-templated-strings
---
#@ def macosx_sdk_component():
builds:
  default:
    configure: |
      mkdir -p "$BUILD_DIR"
    install: |
      # echo "TODO: macosx sdk" && exit 1
      # create-package.sh Xcode_9.xip
      extract.sh --into "${TMP_ROOT}${ORCHESTRA_ROOT}" "(@= sdk_archive_name @)"
add_to_path: "$ORCHESTRA_DOTDIR/support/repackage-apple-sdk"
#@ end
